src/components/Button/Button.tsx

feat(button): add type prop

---

src/components/Tabs/Tab.tsx
src/components/Tabs/TabLabel.tsx

Mainy to prevent bootstrap reboot to mess with our styles.

Add Tabs accessibility

---

src/components/Filters/FilterRow/FilterRow.tsx
src/components/Filters/FilterRow/FilterRow.types.ts
src/components/Filters/Filters.tsx

fix(Filters): fix setting of component default value

---

src/components/layout/Col/Col.tsx
src/components/layout/Row/Row.tsx

fix(layout): pass all props to Col and Row

---

src/components/Datatable/Pagination/Pagination.tsx

fix(Pagination): trigger page input on Enter

---

src/components/forms/SearchBar/SearchBar.test.tsx

https://zitenote.atlassian.net/browse/FEP-1640

test(SearchBar): fix test errors for icons

---

src/components/Datatable/Datatable.tsx
src/components/Datatable/Datatable.types.ts
src/components/Datatable/mocks/controlModule.ts
src/components/forms/SearchBar/SearchBar.stories.tsx
src/components/forms/SearchBar/SearchBar.test.tsx
src/components/forms/SearchBar/SearchBar.tsx
src/components/forms/SearchBar/SearchBar.types.ts
src/components/forms/SearchBar/mocks.ts
src/hooks/useMounted.ts

https://zitenote.atlassian.net/browse/FEP-1642

feat(Datatable): connect filter suggestions to SearchBar

---

src/components/forms/SearchBar/SearchBar.tsx

https://zitenote.atlassian.net/browse/FEP-1652

fix(SearchBar): clear icon styles

---

src/components/Datatable/ControlModule/ControlModule.tsx
src/components/Datatable/ToolsTabItem/ToolsTabItem.tsx

https://zitenote.atlassian.net/browse/FEP-1663

fix(ToolTabItem): styles and undefined func onToolActivate

---

package.json
rollup.config.js
src/components/Filters/components/DateRangePicker/DateRangePicker.tsx
src/components/Filters/components/DateRangePicker/styles.ts
src/components/Filters/components/SingleDatePicker/SingleDatePicker.tsx
src/components/Filters/components/TagsInput/TagsInput.tsx
yarn.lock

I had no luck with setting of postcss plugin so I drop it together with imported css modules. It turned out there isn't needed to define a lot, mainly position of triangle pointer. I've also add UX improvement for tags input.

fix: filters tweaks

---

src/components/Datatable/ControlsModule/ControlsModule.tsx
src/components/Filters/Filters.tsx
src/components/Filters/Filters.types.ts

~~I had to make a deep copy of filteringStoreState because it is read only with reference to store. Value is then saved to Filters state and mutated.~~
Filters state is not mutated.

fix: remove reference of filters state to DT store

---

package.json
src/components/Filters/Filters.test.tsx
src/components/Filters/StateButton/StateButton.tsx
src/components/Filters/mocks/options.ts
yarn.lock

I have introduced library `react-select-event` from `testing-library` ecosystem to test `react-select`
https://testing-library.com/docs/ecosystem-react-select-event

test(Filters): cover by unit tests

---

src/components/FullscreenModal/FullscreenModal.stories.tsx
src/components/FullscreenModal/FullscreenModal.tsx
src/components/FullscreenModal/FullscreenModal.types.ts
src/components/FullscreenModal/hooks/useModal.tsx
src/components/Tooltip/TooltipPopup.tsx
src/hooks/components/DropdownPane.tsx

fix(portals): fix portals stacking

---

src/components/FullscreenModal/hooks/useModal.test.tsx
src/components/FullscreenModal/hooks/useModal.ts

fix(FullscreenModal): freeze body when modal is open

---

src/components/Tabs/TabLabel.tsx

fix(TabLabel): remove focus state css

---

src/components/Button/Button.stories.mdx
src/components/Collapsible/Collapsible.stories.mdx
src/components/Datatable/Datatable.stories.mdx
src/components/Filters/Filters.stories.mdx
src/components/FullscreenModal/FullscreenModal.stories.mdx
src/components/HexGrade/HexGrade.stories.mdx
src/components/Tabs/Tabs.stories.mdx
src/components/Toast/Toast.stories.mdx
src/components/Tooltip/Tooltip.stories.mdx
src/components/forms/Checkbox/Checkbox.stories.mdx
src/components/forms/Input/Input.stories.mdx
src/components/forms/Password/Password.stories.mdx
src/components/forms/Radio/Radio.stories.mdx
src/components/forms/SearchBar/SearchBar.stories.mdx
src/components/forms/Select/Select.stories.mdx
src/components/forms/Switch/Switch.stories.mdx
src/components/forms/TextArea/TextArea.stories.mdx
src/components/layout/layout.stories.mdx
src/components/typography/Text/typography.stories.mdx

Adding standalone documentation pages to top level components in Storybook to reference existing design documentation in Confluence and Figma

docs(storybook): barebones doc pages

---

package.json
yarn.lock

chore(deps): bump ansi-html from 0.0.7 to 0.0.8

---

src/components/forms/MultiValueInput/MultiValue.tsx
src/components/forms/MultiValueInput/MultiValueInput.tsx

fix(MultiValueInput): add keyboard handling for removing values

---

src/components/Button/StyledButton.tsx

fix(Button): fix disabled state when used with router

---

src/components/SemanticModal/SemanticModal.stories.tsx
src/components/SemanticModal/SemanticModal.tsx
src/components/SemanticModal/SemanticModal.types.ts

implements https://zitenote.atlassian.net/browse/UXD-376

feat(SemanticModal): add buttonColor option for primary button

---

visual-regressions/Dockerfile
visual-regressions/bin/take-and-check-in-docker-ci.sh
visual-regressions/bin/take-and-check-in-docker.sh
visual-regressions/bin/take-and-update-in-docker.sh

~~Do not merge!~~
~~Contains unwanted changes that only aim to test differences between rendering on local & GH actions!~~
Changes removed, retested

Abykov try use prebuilt image

---

.storybook/preview.tsx
src/codeExamples/replacingFlexContainer.stories.mdx
src/components/layout/Stack/Stack.stories.tsx

Evangelizing our design system through code examples

Mnau mnau@code examples

---

src/components/typography/Heading/Heading.tsx

feat(H4): change weight to semibold

---

.betterer/.betterer.results
src/components/Banner/Banner.enums.ts
src/components/Banner/Banner.tsx
src/components/Banner/Banner.types.ts
src/components/Toast/Toast.enums.ts
src/components/Toast/Toast.tsx
src/components/Toast/Toast.types.ts
src/components/_internal/BaseToastBanner/BaseToastBanner.enums.ts
src/components/_internal/BaseToastBanner/BaseToastBanner.tsx
src/components/_internal/BaseToastBanner/BaseToastBanner.types.ts
src/components/_internal/BaseToastBanner/index.ts

[Closes](https://zitenote.atlassian.net/browse/UXD-411)

refactor(Toast/Banner): refactor common code

---

src/components/Button/Button.tsx

[UXD-505](https://zitenote.atlassian.net/browse/UXD-505)

fix(UXD-505): Fix button component 'as' prop

---

package.json
yarn.lock

Implements [UXD-483](https://zitenote.atlassian.net/browse/UXD-483)

chore(dependencies): update to the closest patch version

---

src/components/Datatable/Datatable.test.tsx
src/components/Datatable/Table/Table.tsx

This reverts commit 39cce3b0131cf01f8db14aca1379d53667bf5897.

Revert "fix(Datatable): reset selection on data change"

---

CHANGELOG.md
package.json
src/components/Datatable/BatchModule/BatchActions/BatchActions.test.tsx
src/components/Datatable/BatchModule/BatchActions/BatchActions.tsx
src/components/Datatable/BatchModule/BatchActions/BatchActions.types.ts
src/components/Datatable/Datatable.test.tsx
src/components/Datatable/Datatable.types.ts
src/components/Datatable/mocks/actions.ts

feat(Datatable): pass selection reset as action argument

---

src/components/forms/Range/Range.tsx

Fixes https://zitenote.atlassian.net/browse/SIG-312
https://user-images.githubusercontent.com/28569881/161137356-019c2e65-1b47-445a-b378-c197af6e5808.mov

fix(Range): improve keyboard accessibility

---

src/components/Stepper/Stepper.stories.tsx
src/components/Stepper/Stepper.test.tsx

This PR fixes Stepper flaky tests. 
[https://zitenote.atlassian.net/browse/UXD-472](url)

chore(tests): fix Stepper flaky tests

---

.husky/commit-msg
.husky/pre-commit
package.json
yarn.lock

implements https://zitenote.atlassian.net/browse/UXD-495

chore(dependencies): update husky

---

rollup.config.js

BREAKING CHANGE: fixes the build as previous versions weren't working

build(terser): fix the terser build

---

.github/workflows/CD.yaml

BREAKING CHANGE: fixes the build as previous versions weren't working

build(ci): fix the cache hash

---

src/components/Drawer/Drawer.stories.tsx

docs(Drawer): add subheader example

---

package.json
yarn.lock

chore(package): upgrade @fluentui/react-component-ref to v0.62.0

---

src/hooks/hooks.stories.mdx
src/hooks/index.ts
src/index.ts

This PR exports usePortal hook and documents hook's usage in Storybook

feat: export usePortal hook

---

package.json
yarn.lock

chore(package): upgrade polished to v4.2.2

---

src/components/Tabs/Tab.tsx
src/components/_internal/BaseTabs/BaseTabLabel.tsx

This PR fixes color for hover and selected state for Tabs. 
[Closes](https://zitenote.atlassian.net/browse/UXD-552)

fix(Tabs): change hover and selected colors

---

src/components/forms/Switch/Switch.tsx
src/theme/forms.ts
src/theme/forms.types.ts

implements https://zitenote.atlassian.net/browse/UXD-551

feat(Switch): add hover and pressed styles

---

src/components/Dropdown/ControlledDropdown.stories.tsx
src/components/Dropdown/Dropdown.tsx
src/components/Dropdown/Dropdown.types.ts
src/components/_internal/BaseDropdownMenu/DropdownMenu.tsx
src/components/_internal/BaseTable/columns/actionsColumn.tsx

Note: this needs to be rebased once the buttonsPageCount changes are merged, so please ignore those

feat(Datatable): Add hide dropdown on action item click

---

src/components/Banner/Banner.stories.tsx
src/components/Banner/Banner.tsx

feat(Banner): allow to consume custom props

---

src/components/Datatable/components/Search/Search.test.tsx
src/components/Datatable/components/Search/Search.tsx

fix(Datatable): allow search being called with empty value

---

src/components/Signal/Signal.tsx
src/components/Signal/Signal.types.ts

part one for https://zitenote.atlassian.net/browse/UXD-719

feat(Signal): add title for accessibility

---

src/components/forms/Checkbox/Checkbox.tsx
src/components/forms/Radio/Radio.tsx

implements https://zitenote.atlassian.net/browse/UXD-738

feat(Radio & Checkbox): add focus state

---

src/hooks/index.ts

I need this one to close the side drawer in platform on outer click

feat(useOuterCallback): export useOuterCallback hook

---

src/hooks/useOuterCallback.mdx

added docs after the function was exported

docs(useOuterCallback): add docs

---

src/hooks/useOuterCallback.stories.mdx

the filename didn't have .stories.mdx so it didn't show in the storybook

docs(useOuterCallback): change the file name

---

src/components/Card/CardHeader.tsx

fix(Card): use smaller card title

---

src/components/Datatable/ControlsModule/ControlsModule.tsx
src/components/Datatable/Datatable.stories.tsx
src/components/Datatable/Datatable.tsx
src/components/Datatable/Datatable.types.ts
src/components/Datatable/components/Search/Search.test.tsx
src/components/forms/SearchBar/SearchBar.stories.tsx
src/components/forms/SearchBar/SearchBar.tsx

Small fixes for Datatable component

---

src/components/Datatable/ControlsModule/ControlsModule.test.tsx
src/components/Datatable/ControlsModule/ControlsModule.tsx

fix(Datatable): trigger search when default value is provided

---

src/components/forms/SearchBar/SearchBar.tsx
src/components/forms/SearchBar/SearchBar.types.ts

fix(SearchBar): add shouldTriggerSearchOnMount prop

---

package.json
rollup.config.js
src/components/Banner/Banner.tsx
src/components/Card/CardMedia.tsx
src/components/Datatable/BatchModule/ElementCounter/ElementCounter.tsx
src/components/Datatable/ControlsModule/ControlsModule.tsx
src/components/Datatable/Datatable.tsx
src/components/Datatable/Table/Table.tsx
src/components/Datatable/Table/components/TableCheckbox.tsx
src/components/Table/Table.tsx
src/components/_internal/BaseTable/Body/Body.tsx
src/components/_internal/BaseTable/Head/Head.tsx
src/components/_internal/BaseTable/renderers/CellRenderer.tsx
src/components/_internal/BaseTable/renderers/LinkRenderer.tsx
src/components/_internal/BaseTable/renderers/MultiValueRenderer.tsx
src/components/forms/Select/CreatableSelect.tsx
src/components/forms/Select/Select.tsx
src/types/action.types.ts
yarn.lock

refactor: add displayNames to minified components

---

src/components/layout/Grid/Grid.stories.tsx
src/components/layout/Grid/Grid.tsx

implements https://zitenote.atlassian.net/browse/UXD-926

feat(Grid): throw Error on cols=1

---

src/components/forms/Checkbox/Checkbox.stories.tsx
src/components/forms/Checkbox/Checkbox.tsx

implements https://zitenote.atlassian.net/browse/UXD-1010

docs(Checkbox): change role and add descriptions to Storybook

---

src/components/_internal/BaseButton/BaseStyledButton.tsx

implements https://zitenote.atlassian.net/browse/UXD-1022

fix(Button): fix focus-visible outline

---

src/components/Button/Button.stories.tsx
src/components/UserAvatar/UserAvatar.tsx
src/components/_internal/BaseButton/BaseButton.tsx
src/components/_internal/BaseButton/BaseButton.types.ts
src/components/_internal/BaseSingleDatePicker/CustomHeader.tsx

implements https://zitenote.atlassian.net/browse/UXD-1014
[UXD-1014]: https://zitenote.atlassian.net/browse/UXD-1014?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(Button): add aria-label to icon only buttons

---

.github/workflows/CD.yaml
scripts/generate-index.js

Several attempt to make the auto-release wokring

build: update and reenable docs release

---

yarn.lock

chore(deps): bump json5 from 2.2.1 to 2.2.3

---

src/components/Datatable/BatchModule/ElementCounter/ElementCounter.test.tsx
src/components/Datatable/BatchModule/ElementCounter/ElementCounter.tsx
src/components/Datatable/Datatable.test.tsx

implements https://zitenote.atlassian.net/browse/UXD-1045

feat(ElementCounter): change H4 to text size h4

---

src/components/_internal/BaseDropdownMenu/DropdownMenu.tsx

This reverts commit 965c679093d7769a8964dc36c2f4c9d9caa8cb89.

Revert "feat(DropdownMenu): add keyboard navigation"

---

.yarnrc.yml
package.json
tsconfig.build.json
tsconfig.json
vite.config.ts
yarn.lock

chore(typescript): upgrade ts to v5.0.4

---

visual-regressions/yarn.lock
yarn.lock

chore(package): upgrade semver v5 and v6

---

yarn.lock

chore(package): use word-wrap fork

---

src/components/Accordion/Accordion.stories.tsx
src/components/Accordion/Accordion.tsx
src/components/Accordion/Accordion.types.ts

fix(Accordion): make 'openItems' act as value

---

package.json
src/components/layout/Col/Col.tsx
src/components/layout/Row/Row.tsx
yarn.lock

refactor(layout): remove 'reflexbox' code

---

src/components/CloseButton/CloseButton.tsx

feat(CloseButton): add type attribute

---

src/components/Signal/Signal.test.tsx
src/components/Signal/Signal.tsx

fix(Signal): handle unknown value gracefully

---

src/components/Datatable/components/ColumnsControls/hooks/useColumnVisibility.ts

fix(Datatable): fix column visibility state

---

.storybook/preview.tsx
src/components/DatatableV2/Datatable.tsx
src/components/DatatableV2/Datatable.types.ts
src/components/DatatableV2/header/HeaderCell.tsx
src/components/DatatableV2/header/HeaderCellSortLabel.tsx
src/components/DatatableV2/hooks/useDatatable.ts
src/components/DatatableV2/hooks/useOptions.ts
src/components/DatatableV2/mocks/externalData.ts
src/components/DatatableV2/stories/Pagination.stories.tsx
src/components/DatatableV2/stories/Template.tsx
src/components/DatatableV2/tests/pagination.test.tsx
src/components/DatatableV2/tests/sorting.test.tsx
src/components/DatatableV2/toolbar/Pagination.tsx
src/hooks/useLogger.test.tsx
src/hooks/useLogger.ts

feat(DatatableV2): implement pagination

---

src/components/DatatableV2/Datatable.tsx
src/components/DatatableV2/Datatable.types.ts
src/components/DatatableV2/hooks/useOptions.ts
src/components/DatatableV2/mocks/externalData.ts
src/components/DatatableV2/stories/Pagination.stories.tsx
src/components/DatatableV2/stories/Sorting.stories.tsx
src/components/DatatableV2/tests/pagination.test.tsx
src/components/DatatableV2/toolbar/Pagination.tsx

feat(DatatableV2): implement rows per page select

---

src/components/DatatableV2/Datatable.types.ts
src/components/DatatableV2/buttons/SelectButton.tsx
src/components/DatatableV2/hooks/useDatatable.ts
src/components/DatatableV2/hooks/useDisplayColumns.tsx
src/components/DatatableV2/hooks/useOptions.ts
src/components/DatatableV2/stories/Pagination.stories.tsx
src/components/DatatableV2/stories/Selection.stories.tsx
src/components/DatatableV2/stories/Sorting.stories.tsx
src/components/DatatableV2/tests/selection.test.tsx

feat(DatatableV2): implement selection

---

.eslintrc.js
src/components/DatatableV2/Datatable.types.ts
src/components/DatatableV2/columns.utils.ts
src/components/DatatableV2/header/HeaderCell.tsx
src/components/DatatableV2/header/HeaderCellResizeHandler.tsx
src/components/DatatableV2/hooks/useOptions.ts
src/components/DatatableV2/menus/ColumnActionsMenu.tsx
src/components/DatatableV2/stories/ColumnResizing.stories.tsx
src/components/DatatableV2/table/Table.tsx
src/components/DatatableV2/tests/columnPinning.test.tsx
src/components/DatatableV2/tests/columnResizing.test.tsx

feat(DatatableV2): implement column resizing

---

src/components/DatatableV2/Datatable.types.ts
src/components/DatatableV2/buttons/SelectButton.tsx
src/components/DatatableV2/header/HeaderCell.tsx
src/components/DatatableV2/header/HeaderCellSortButton.tsx
src/components/DatatableV2/hooks/useDatatable.ts
src/components/DatatableV2/hooks/useDisplayColumns.tsx
src/components/DatatableV2/inputs/IndeterminateCheckbox.tsx
src/components/DatatableV2/menus/ColumnActionsMenu.tsx
src/components/DatatableV2/panels/Settings.tsx
src/components/DatatableV2/panels/SettingsItem.tsx
src/components/DatatableV2/stories/ColumnPinning.stories.tsx
src/components/DatatableV2/stories/ColumnResizing.stories.tsx
src/components/DatatableV2/stories/ColumnSettingsPanel.stories.tsx
src/components/DatatableV2/stories/ColumnVisibility.stories.tsx
src/components/DatatableV2/stories/Pagination.stories.tsx
src/components/DatatableV2/stories/Sorting.stories.tsx
src/components/DatatableV2/stories/Template.tsx
src/components/DatatableV2/table/Table.tsx
src/components/DatatableV2/tests/columnSettingsPanel.test.tsx
src/components/DatatableV2/tests/columnVisibility.test.tsx
src/components/DatatableV2/tests/mocks.ts
src/hooks/index.ts
src/hooks/useDebounce.stories.mdx
src/hooks/useDebounce.ts

feat(DatatableV2): implement column settings panel

---

.storybook/preview.tsx
src/components/DatatableV2/Datatable.types.ts
src/components/DatatableV2/body/Body.tsx
src/components/DatatableV2/body/BodyCell.tsx
src/components/DatatableV2/body/Skeleton.tsx
src/components/DatatableV2/buttons/SelectButton.tsx
src/components/DatatableV2/columns.utils.ts
src/components/DatatableV2/header/HeaderCell.tsx
src/components/DatatableV2/hooks/useDatatable.ts
src/components/DatatableV2/stories/Loading.stories.tsx
src/components/DatatableV2/table/ProgressBar.tsx
src/components/DatatableV2/table/Table.tsx
src/components/DatatableV2/table/TableRoot.tsx
src/components/DatatableV2/table/TableSurface.tsx

feat(DatatableV2): implement loading states

---

src/components/DatatableV2/Datatable.types.ts
src/components/DatatableV2/buttons/IconButton.tsx
src/components/DatatableV2/buttons/RowActionsButton.tsx
src/components/DatatableV2/columns.utils.ts
src/components/DatatableV2/hooks/useDatatable.ts
src/components/DatatableV2/hooks/useDisplayColumns.tsx
src/components/DatatableV2/hooks/usePersistentState.ts
src/components/DatatableV2/menus/ColumnActionsMenu.tsx
src/components/DatatableV2/menus/RowActionsMenu.tsx
src/components/DatatableV2/menus/menuElements.tsx
src/components/DatatableV2/stories/RowActions.stories.tsx
src/components/Tooltip/Tooltip.tsx
src/components/Tooltip/Tooltip.types.ts

feat(DatatableV2): implement row actions

---

src/components/DatatableV2/Datatable.types.ts
src/components/DatatableV2/header/HeaderCell.tsx
src/components/DatatableV2/stories/HeaderTooltip.stories.tsx

feat(DatatableV2): implement header tooltip

---

src/components/DatatableV2/body/BodyRow.tsx
src/components/DatatableV2/buttons/IconButton.tsx
src/components/DatatableV2/buttons/SelectButton.tsx
src/components/DatatableV2/columns.utils.ts
src/components/DatatableV2/header/HeaderCell.tsx
src/components/DatatableV2/hooks/useDisplayColumns.tsx
src/components/DatatableV2/hooks/useOptions.ts
src/components/DatatableV2/table/TableRoot.tsx
src/components/DatatableV2/table/TableSurface.tsx
src/components/DatatableV2/tests/selection.test.tsx
src/components/DatatableV2/toolbar/Pagination.tsx
src/components/DatatableV2/toolbar/Selection.tsx
src/components/Tooltip/Tooltip.tsx

feat(DatatableV2): style selection toolbar

---

src/components/Drawer/Drawer.stories.tsx
src/components/Drawer/Drawer.tsx
src/components/Modal/Modal.stories.tsx
src/components/Modal/Modal.tsx
src/components/Tooltip/Tooltip.tsx
src/contexts/FloatingContext.tsx

fix(Tooltip): set correct z-index in floating elements

---

src/components/DatatableV2/Datatable.types.ts
src/components/DatatableV2/body/BodyCell.tsx
src/components/DatatableV2/columns.utils.ts
src/components/DatatableV2/header/HeaderCell.tsx
src/components/DatatableV2/hooks/useDatatable.ts
src/components/DatatableV2/hooks/useHasHozintalScroll.ts
src/components/DatatableV2/table/Table.tsx
src/components/DatatableV2/table/TableRoot.tsx
src/components/DatatableV2/table/TableSurface.tsx
src/components/DatatableV2/toolbar/Selection.tsx

Datatable - horizontal scroll

---

src/components/DatatableV2/columns.utils.ts
src/components/DatatableV2/menus/ColumnActionsMenu.tsx
src/components/DatatableV2/panels/Settings.tsx
src/components/DatatableV2/panels/SettingsItem.tsx
src/components/DatatableV2/panels/SettingsItems.tsx
src/components/DatatableV2/stories/Template.tsx
src/components/DatatableV2/tests/columnSettingsPanel.test.tsx

fix(DatatableV2): prevent hiding all columns

---

src/components/forms/Checkbox/Checkbox.tsx
src/components/forms/Label/Label.tsx
src/components/typographyLegacy/Heading/Heading.stories.tsx
src/components/typographyLegacy/Heading/Heading.tsx
src/components/typographyLegacy/Heading/Heading.types.tsx
src/components/typographyLegacy/Link/Link.tsx
src/components/typographyLegacy/Link/Link.types.ts

fix(types): add children prop

---

src/components/Drawer/Drawer.tsx

https://github.com/securityscorecard/design-system/assets/1456829/35a1e63a-d340-4933-9912-96de2bfcb49a
https://github.com/securityscorecard/design-system/assets/1456829/876ac2d2-19f2-4b08-ac51-0a74b9d5c7a5
https://zitenote.atlassian.net/browse/UXD-1446

fix(Drawer): fix backdrop flickering with outside clicks

---

src/components/Breadcrumbs/BreadcrumbItem.tsx

fix(Breadcrumbs): make item icon optional

---

src/components/DatatableV2/Datatable.types.ts
src/components/DatatableV2/buttons/IconButton.tsx
src/components/DatatableV2/buttons/RowActionsButton.tsx
src/components/DatatableV2/menus/RowActionsMenu.tsx
src/components/DatatableV2/menus/menuElements.tsx
src/components/DatatableV2/stories/RowActions.stories.tsx

feat(Datatable): extend RowActions API

---

package.json
src/components/Drawer/Drawer.tsx
src/components/Modal/Modal.tsx
src/components/_internal/BaseFocusTrap/BaseFocusTrap.tsx
src/components/_internal/BaseFocusTrap/BaseFocusTrap.types.tsx
src/components/_internal/BaseFocusTrap/index.tsx
yarn.lock

https://github.com/securityscorecard/design-system/assets/1456829/d190420d-b1ba-4532-92f3-9e9acec8caf5

feat(dialogs): implement focus trap for Modal and Drawer

---

src/components/DatatableV2/hooks/useDatatable.ts

https://github.com/securityscorecard/design-system/assets/1456829/bcaf1257-fd06-458b-8abd-de0473d6c22d

fix(DatatableV2): exit fullscreen mode on ESC

---

src/overview.stories.mdx

docs(Overview): fix overview page

---

src/theme/colors.ts
src/tokens/color.css

feat(colors): add surface interaction colors

---

src/components/DatatableV2/table/TableSurface.tsx
src/theme/space.ts
src/tokens/space.css

fix(space): adapt to 4px grid

---

src/components/DatatableV2/panels/DetailPanel.tsx
src/components/DatatableV2/table/TableRoot.tsx

BEFORE
https://github.com/user-attachments/assets/d557768e-5300-40f8-bb28-d2d43baff2e3
AFTER
https://github.com/user-attachments/assets/92184f23-3f5f-44f4-9479-8b881b46776c
Closes UXD-1544

fix(DatatableV2): make detail panel content sticky

---

package.json
src/components/layout/Col/Col.tsx
src/components/layout/Row/Row.tsx
src/tokens/space.css
yarn.lock

remove unused dependencies

---

src/components/DatatableV2/table/TableRoot.tsx
src/components/DatatableV2/table/TableSurface.tsx
src/components/DatatableV2/toolbar/Selection.tsx
src/components/TreeView/components/TreeItem.tsx
src/components/UserAvatar/UserAvatar.tsx
src/theme/colors.ts
src/tokens/color.css

refactor(token): change primary scale numbering

---

src/components/_internal/BaseDropdownMenu/DropdownMenu.test.tsx
src/components/_internal/BaseDropdownMenu/DropdownMenu.tsx
src/components/_internal/BaseDropdownMenu/menuElements.tsx

chore(BaseDropdownMenu): remove prop-types

---

package.json
visual-regressions/yarn.lock
yarn.lock

chore(deps): fix dependabot alerts

---

src/components/Filters/BottomBar/BottomBar.tsx
src/components/Filters/DisabledOperator/DisabledOperator.tsx
src/components/Filters/FilterRow/FilterRow.tsx
src/components/Filters/Filters.tsx
src/components/Filters/Filters.types.ts
src/components/Filters/StateButton/StateButton.tsx
src/components/Filters/components/Count/Count.tsx
src/components/Filters/components/Input/Input.tsx
src/components/Filters/components/Integer/Integer.tsx
src/components/Filters/components/Number/Number.tsx
src/components/Filters/components/Number/Number.types.ts
src/components/Filters/components/TagsInput/TagsInput.tsx

chore(Filters): remove prop-types

---

src/components/_internal/BaseSingleDatePicker/SingleDatePicker.tsx

chore(BaseSingleDatePicker): remove prop-types

---

src/components/_internal/BaseDateRangePicker/BaseDateRangePicker.tsx
src/components/_internal/BaseDateRangePicker/BaseDateRangePicker.types.ts

chore(BaseDateRangePicker): remove prop-types

---

src/components/Table/Table.tsx
src/components/Table/Table.types.ts

chore(Table): remove prop-types

---

src/components/_internal/BaseTable/BaseTable.types.ts
src/components/_internal/BaseTable/Footer/Footer.tsx
src/components/_internal/BaseTable/Footer/GoToPage.tsx
src/components/_internal/BaseTable/components/TooltipWrapper.tsx
src/components/_internal/BaseTable/renderers/CellRenderer.tsx
src/components/_internal/BaseTable/renderers/renderers.stories.tsx
src/components/_internal/BaseTable/renderers/renderers.types.ts

chore(BaseTable): remove prop-types

---

src/components/Banner/Banner.tsx

chore(Banner): remove prop-types

---

src/components/CloseButton/CloseButton.tsx

chore(CloseButton): remove prop-types

---

src/components/ControlDropdown/ControlDropdown.tsx

chore(ControlDropdown): remove prop-types

---

src/components/Drawer/Drawer.tsx

chore(Drawer): remove prop-types

---

src/components/Pill/Pill.tsx

fix(Pill): improve backwards compatibility with previous versions

---

src/components/Heading/Heading.tsx

chore(Heading): remove prop-types

---

src/components/HexGrade/HexGrade.tsx

chore(HexGrade): remove prop-types

---

src/components/HintTooltip/HintTooltip.tsx

chore(HintTooltip): remove prop-types

---

src/components/layout/Center/Center.tsx
src/components/layout/Cluster/Cluster.tsx
src/components/layout/Col/Col.tsx
src/components/layout/Grid/Grid.tsx
src/components/layout/Inline/Inline.tsx
src/components/layout/Padbox/Padbox.tsx
src/components/layout/Stack/Stack.tsx

chore(layout): remove prop-types

---

src/components/Loading/Loading.tsx

chore(Loading): remove prop-types

---

src/components/Modal/Modal.tsx

chore(Modal): remove prop-types

---

src/components/Pagination/PageButtons.tsx
src/components/Pagination/Pagination.tsx
src/components/Pagination/PaginationItem.tsx

chore(Pagination): remove prop-types

---

src/components/Paragraph/Paragraph.tsx

chore(Paragraph): remove prop-types

---

src/components/Pill/Pill.tsx
src/components/Pill/PillRemoveButton.tsx

chore(Pill): remove prop-types

---

src/components/SemanticModal/SemanticModal.tsx

chore(SemanticModal): remove prop-types

---

src/components/SortableList/SortableItem.tsx
src/components/SortableList/SortableList.tsx

chore(SortableList): remove prop-types

---

src/components/Spinner/Spinner.tsx

chore(Spinner): remove prop-types

---

src/components/StatusDot/StatusDot.tsx

chore(StatusDot): remove prop-types

---

src/components/Stepper/Step.tsx
src/components/Stepper/StepBullet.tsx
src/components/Stepper/Stepper.tsx

chore(Stepper): remove prop-types

---

src/components/Tabs/Tab.tsx
src/components/Tabs/Tabs.tsx

chore(Tabs): remove prop-types

---

src/components/Text/Text.tsx

chore(Text): remove prop-types

---

src/hooks/components/DropdownPane.tsx

chore(components): remove prop-types

---

package.json
src/components/DatatableV2/.eslintrc
src/components/forms/SegmentedToggle/SegmentedToggle.test.tsx
yarn.lock

chore(package): remove prop-types package

---

.commitlintrc.json
.storybook/preview.tsx
docs/localization.mdx
jest.setup.ts
package.json
src/components/Filters/BottomBar/BottomBar.tsx
src/components/Filters/FilterRow/FilterRow.tsx
src/components/Filters/Filters.test.tsx
src/components/Filters/StateButton/StateButton.tsx
src/components/Filters/components/Count/Count.tsx
src/components/Filters/components/Input/Input.tsx
src/components/Filters/components/Integer/Integer.tsx
src/components/Filters/components/Number/Number.tsx
src/components/Filters/components/TagsInput/TagsInput.tsx
src/components/Filters/data/operatorOptions.ts
src/hooks/useSafeTranslation.ts
src/locales/cs-CZ.ts
src/locales/en-US.ts
src/locales/es-ES.ts
src/locales/ja-JP.ts
src/locales/pt-BR.ts
src/types/definitions/i18next.d.ts
vite.config.mts
yarn.lock

feat(i18n): enable localization of the design system

---

src/components/DatatableV2/table/ProgressBar.tsx

refactor(DatatableV2): replace defaultProps property

---

src/components/forms/Input/Input.tsx

refactor(Input): replace defaultProps property

---

src/components/forms/Select/CreatableSelect.tsx
src/components/forms/Select/Select.tsx

refactor(Select): replace defaultProps property

---

src/components/layout/Center/Center.tsx

refactor(Center): replace defaultProps property

---

src/components/layout/Grid/Grid.tsx

refactor(Grid): replace defaultProps property

---

src/components/layout/Inline/Inline.tsx

refactor(Inline): replace defaultProps property

---

src/components/layout/Padbox/Padbox.tsx

refactor(Padbox): replace defaultProps property

---

src/components/Paragraph/Paragraph.tsx

refactor(Paragraph): replace defaultProps property

---

src/components/Spinner/Spinner.tsx

refactor(Spinner): replace defaultProps property

---

src/components/layout/Cluster/Cluster.tsx

refactor(Cluster): replace defaultProps property

---

src/components/Text/Text.tsx

refactor(Text): replace defaultProps property

---

src/components/DatatableV2/panels/Settings.tsx

fix(DatatableV2): make header sticky in settings panel

---

src/components/DatatableV2/buttons/ExpandAllButton.tsx
src/components/DatatableV2/buttons/ExpandButton.tsx
src/components/DatatableV2/header/HeaderCell.tsx
src/components/DatatableV2/hooks/useDisplayColumns.tsx

fix(DatatableV2): fix Rendered fewer hooks than expected issue

---

src/components/Badge/Badge.stories.tsx
src/components/Badge/Badge.tsx

feat(Badge): add option to offset position

---

.storybook/blocks/OverviewCard.tsx
.storybook/blocks/components.tsx
docs/overview.mdx

After deployment SB to GH Pages we found out the issue with broken links that were working normally in local development.
Ref NOTICKET

docs(overview): fix links leading to components docs

---

src/components/FileSelector/FileSelector.tsx

fix(FileSelector): prevent submit form on click

---

src/components/DatatableV2/toolbar/TopToolbar.tsx

fix(DatatableV2): expose item count for tests

---

src/components/Filters/FilterRow/FilterRow.tsx
src/components/Filters/FilterRow/filterRow.test.tsx

fix(Filters): make operator parsing case insensitive

---

src/components/TreeView/TreeView.test.tsx
src/components/TreeView/TreeView.tsx

fix(TreeView): rerender component when new data are passed

---

src/components/HexGrade/HexGrade.tsx

fix(HexGrade): allow passing additional props UXD-1668

---

src/components/forms/SegmentedToggle/SegmentedToggle.tsx

fix(SegmentedToggle): fit root width to content size UXD-1673

---

src/components/ElementLabel/ElementLabel.tsx
src/types/utils.types.ts

fix(ElementLabel): allow element polymorphism UXD-1671

---

src/components/forms/SearchBar/SearchBar.tsx

fix(SearchBar): fix clear button hover state UXD-1692

---

src/components/Breadcrumbs/Breadcrumbs.test.tsx
src/components/Datatable/BatchModule/BatchActions/BatchActions.test.tsx
src/components/Datatable/BatchModule/ElementCounter/ElementCounter.test.tsx
src/components/DateRangePicker/DateRangePicker.test.tsx
src/components/Filters/Filters.test.tsx
src/components/Toast/Toast.test.tsx
src/components/Tooltip/Tooltip.test.tsx
src/components/TreeView/TreeView.test.tsx
src/components/TreeView/components/CollapsibleHandle.test.tsx
src/components/_internal/BaseDropdownMenu/DropdownMenu.test.tsx
src/components/_internal/BaseTable/renderers/CellRenderer.test.tsx
src/components/_internal/BaseTable/renderers/LinkRenderer.test.tsx
src/components/_internal/BaseTable/renderers/MultiValueRenderer.test.tsx
src/components/forms/Range/Range.test.tsx

test(unit): replace fireEvent with userEvent lib UXD-1689

---

src/components/DatatableV2/Datatable.types.ts
src/components/DatatableV2/stories/ColumnActions.stories.tsx
src/components/DatatableV2/stories/ColumnOrdering.stories.tsx
src/components/DatatableV2/stories/ColumnPinning.stories.tsx
src/components/DatatableV2/stories/ColumnResizing.stories.tsx
src/components/DatatableV2/stories/ColumnSettingsPanel.stories.tsx
src/components/DatatableV2/stories/ColumnVisibility.stories.tsx
src/components/DatatableV2/stories/DetailPanel.stories.tsx
src/components/DatatableV2/stories/EmptyData.stories.tsx
src/components/DatatableV2/stories/FullscreenMode.stories.tsx
src/components/DatatableV2/stories/HeaderTooltip.stories.tsx
src/components/DatatableV2/stories/Loading.stories.tsx
src/components/DatatableV2/stories/Pagination.stories.tsx
src/components/DatatableV2/stories/PersistentState.stories.tsx
src/components/DatatableV2/stories/RowActions.stories.tsx
src/components/DatatableV2/stories/RowOnClick.stories.tsx
src/components/DatatableV2/stories/Selection.stories.tsx
src/components/DatatableV2/stories/Sorting.stories.tsx
src/components/DatatableV2/stories/TopToolbar.stories.tsx
src/components/DatatableV2/stories/argTypes.ts

fix(DatatableV2): fix type of renderRowSelectionActions UXD-1704

---

src/components/SemanticModal/SemanticModal.test.tsx
src/components/SemanticModal/SemanticModal.tsx

fix(SemanticModal): handle cases when only dismiss button is provided UXD-1705

---

src/components/Card/Card.tsx
src/components/Collapsible/Collapsible.tsx
src/components/Snippet/Snippet.tsx
src/components/_internal/BaseTable/Footer/Footer.tsx
src/components/_internal/BaseToastBanner/BaseToastBanner.tsx
src/components/forms/MultiValueInput/MultiValueInput.tsx
src/components/forms/SegmentedToggle/SegmentedToggle.tsx
src/components/forms/TextArea/TextArea.tsx
src/components/layout/Padbox/Padbox.tsx

I noticed that the types does not work correctly and properties are not suggested by the IDE. This PR fixes this issue.
Closes UXD-1670

fix(Padbox): fix component types UXD-1670

---

src/components/ListView/ListView.test.tsx
src/components/ListView/ListView.tsx

fix(ListView): handle cases when data is not provided UXD-1680

---

src/components/SemanticModal/SemanticModal.test.tsx
src/components/SemanticModal/SemanticModal.tsx

fix(SemanticModal): fix rendering issues for falsy actions PROPS-18724

---

src/components/Datatable/Table/components/TableCheckbox.tsx

fix(a11y): fix TableCheckbox label UXD-1721

---

src/components/Filters/FilterRow/FilterRow.tsx
src/components/Filters/mocks/MockObjectFilter.tsx

fix(a11y): add labels to Filters fields UXD-1714

---

src/components/Loading/Loading.tsx

fix(a11y): add label to Loading progressbar UXD-1712

---

src/components/ScrollView/ScrollView.tsx

fix(a11y): make ScrollView focusable UXD-1713

---

src/components/Snippet/Snippet.tsx

fix(a11y): remove textbox role from Snippet UXD-1715

---

src/components/FileSelectorButton/FileSelectorButton.tsx

fix(a11y): remove button role override in FileSelectorButton UXD-1716

---

src/components/FileSelector/FileSelector.tsx

fix(a11y): mark disabled component in FileSelector properly UXD-1717

---

src/components/Breadcrumbs/Breadcrumbs.tsx

fix(a11y): fix element nesting in Breadcrumbs UXD-1718

---

src/components/DatatableV2/table/Table.tsx

fix(a11y): add label to DatatableV2 progress bar UXD-1720

---

src/components/Datatable/Table/components/TableCheckbox.tsx

fix(a11y): set correct role to checkbox mark in Datatable UXD-1723

---

src/components/Datatable/Table/columns/selectionColumn.tsx
src/components/_internal/BaseTable/columns/actionsColumn.tsx

fix(a11y): fix empty Datatable header text UXD-1725

---

.storybook/test-runner.ts
src/components/ButtonV2/Button.stories.tsx
src/components/Filters/Filters.stories.tsx
src/components/forms/forms.stories.tsx

test(a11y): fix rule disabling UXD-1726

---

src/components/Datatable/Table/Table.tsx

fix(a11y): fix Datatable cells rendering UXD-1727

---

src/components/ControlDropdown/ControlDropdown.tsx
src/components/_internal/BaseTable/Footer/Footer.tsx

fix(a11y): remove footer elements UXD-1728

---

src/components/forms/MultiValueInput/MultiValueInput.tsx

fix(a11y): add disabled attribute to MultiValueInput pills UXD-1730

---

src/components/ListView/ListViewRow.tsx

fix(a11y): add label to ListView row button UXD-1731

---

src/components/TreeView/components/TreeItem.tsx

fix(a11y): add label to TreeView sort handler UXD-1732

---

src/components/DatatableV2/buttons/ExpandAllButton.tsx

fix(a11y): fix empty DatatableV2 header text UXD-1729

---

src/tokens/radii.css
src/tokens/size.css
src/tokens/space.css
src/tokens/tokens.css

feat(tokens): add widget tokens UXD-1736

---

src/components/Signal/Signal.types.ts
src/components/Signal/common.tsx

- Ensure the label is hidden from screen readers.

fix(Signal): hide label from screen reader. PLAT-495

---

src/components/Callout/Callout.tsx

- Ensure the icon is hidden from screen readers.
- Add the aria label prop for the global Callout component.

fix(Callout): add aria attributes. PLAT-529

---

src/components/HintTooltip/HintTooltip.tsx
src/components/HintTooltip/HintTooltip.types.ts
src/components/Tooltip/Tooltip.types.ts

- Reading the tooltip content with the Screen Reader.

refactor(HintTooltip): read tooltip with the screen reader. PLAT-531

---

src/components/Datatable/Table/Table.test.tsx
src/components/Pagination/PageButtons.tsx
src/components/Pagination/PaginationItem.tsx

Adding accessibility enhancements regarding the Screen Reader behavior to the `PageButtons` and `PaginationItem` components

refactor(PageButtons): add a11y behavior. PLAT-703

---

src/components/forms/TextArea/TextArea.tsx

- Ensure the counter is hidden from screen readers.

fix(TextArea): hide counter from screen reader. PLAT-702

---

src/components/Card/Card.tsx
src/components/Card/Card.types.ts

Improving types for the `Card` component.

refactor(Card): improving types. PLAT-752

---

src/components/HintTooltip/HintTooltip.tsx
src/components/Tooltip/Tooltip.tsx
src/components/forms/TextArea/TextArea.tsx

Inproving the platform´s accessibility by adding missing aria attributes and roles.

feat(A11y): improving aria labels. PLAT-756

---

src/components/Datatable/BatchModule/ElementCounter/ElementCounter.tsx
src/components/Tabs/Tab.tsx
src/components/Tabs/Tabs.tsx
src/components/Tabs/Tabs.types.ts

- Improving Accessibility by adding aria labels to the `Tabs` and `Tab` components.

feat(Tabs): adding aria labels. PLAT-846

---

src/components/DatatableV2/header/HeaderCell.tsx
src/components/DatatableV2/header/HeaderCellResizeHandler.tsx
src/components/DatatableV2/tests/sorting.test.tsx
src/components/DatatableV2/toolbar/TopToolbar.tsx

- Improving Accessibility by adding aria labels to the `DatatableV2` component.

feat(DatatableV2): adding aria labels. PLAT-851

---

src/components/forms/Select/Select.test.tsx
src/components/forms/Select/useSelectProps.ts

Remove select prop "on blur" for single select

fix(select): remove conflicting prop. PLAT-872
