securityscorecard/design-system

- src/components/Button/Button.tsx
- src/components/Button/Button.types.ts
- src/components/Icon/Icon.tsx
- src/components/Icon/Icon.types.ts
- src/components/IconButton/IconButton.tsx
When `Icon` based components are used in 3rd-party integration with an extended icon library proptypes are throwing warnings about invalid values.
This PR adding generic `string` type for icon type and icon name props to prevent these warnings.
> fix(Icon): fix proptypes warning when 3rd party icon is used

- package.json
- src/components/Button/Button.tsx
- src/components/Button/Button.types.ts
- src/components/Nav/Nav.stories.tsx
- src/components/Nav/NavItem.tsx
- src/components/Nav/NavItem.types.ts
- src/components/typography/Link/Link.tsx
- src/utils/require-router-link.ts
- tsconfig.json
- yarn.lock
This PR is making `react-router-dom` optional and dynamic dependency, that means you don't have to have router included in your project e.g. Next is using its own router and make `react-router-dom` unnecessary.
When `react-router-dom` is not installed and you try to use either Button or Link component with `to` property and without specified component or tag in `as` property library will throw an error in the console with possible solutions and will not render anything in DOM.
There is one caveat with this solution if you're using this library without `react-router-dom` it will show a warning about missing module in the console. I haven't found a solution to this but a user can disable the warning in Webpack in his application.
> fix(router): make react-router-dom optional

- package.json
- rollup.config.js
- yarn.lock
This PR fixes issue with bundled dependencies(https://github.com/styled-system/styled-system/issues/948) I hit on the ratings platform. It externalizes all dependencies from `package.json` and leaves that on the package manager to handle. As a side effect, it will make the bundled package smaller.
> fix: externalize dependencies from bundle

- src/components/Tabs/Tab.tsx
SSC platform overrides the styles with the default blue color etc. so need to hardcode it here
> fix(tabs): default styles

- src/components/Datatable/ToolsTabItem/ToolsTabItem.tsx
- src/components/Datatable/ToolsTabItem/ToolsTabItem.types.ts
onToolActivate and onToolDeactivate are not required in `ControlsConfig` but required in `ToolsTabItem` 
When missing, we get this error in ui-core
```Uncaught TypeError: Cannot read property 'onToolActivate' of undefined```
> fix(ToolTabItem): require conflict for tool actions

- .github/workflows/publish-storybook.yaml
This PR enables Storybook publishing on release creation. Alpha and Stable versions will be published in different folders. All Alpha version will be published into the `alpha` folder since those releases are fast-changing and there's no point in keeping documentation for every released version. The Stable version will be published into separate folders by their version number which corresponds with the tag name, e.g `v1.0.0`, `v1.3.5` etc. Since we should be able to provide documentation for each stable version in future.
> build(docs): enable Storybook publishing

- CONTRIBUTING.md
Since we've updated our working branch to alpha. Let's change the docs to reflect this also for newcomers, once (if?) we switch back we will need to be mindful to change it back :)
> Rename main branch in contributing docs

- src/components/Datatable/Table/Body/renderers/CellRenderer.test.tsx
- src/components/Datatable/Table/Body/renderers/MultiValueRenderer.test.tsx
- src/components/Tooltip/hooks/useTooltip.tsx
- src/hooks/useDropdown.tsx
- src/theme/DSProvider/DSProvider.stories.mdx
- src/theme/DSProvider/DSProvider.tsx
- src/theme/DSProvider/DSProvider.types.ts
We hit issue with passing custom styled-components into the Tooltip component. Since in platform we are namespacing component to avoid conflicts with legacy SCSS files and portals container is created outside of `#root` element styles (there is no matching selector) are not applied to custom styled-components inside Tooltip and Dropdown components.
> feat(DsProvider): allow DS context configuration

- src/components/FullscreenModal/Header/Header.tsx
> fix: increase modal header z-index

- src/components/Button/StyledButton.tsx
Stops forwarding the ```margin``` React property to the DOM as an HTML attribute.
> fix(Button): stop forwarding margin prop to DOM

- src/components/Filters/components/Input/Input.tsx
- src/components/Filters/components/Number/Number.tsx
- src/components/Filters/components/Select/Select.tsx
We missed this when refactoring Filters from `form` to `div` container. There is no need to keep it there, moreover it was preventing selection in dropdown on enter.
> fix(Filters): remove preventing default in components

- src/components/Datatable/ControlsModule/ControlsModule.tsx
- src/components/Datatable/Table/Table.reducer.ts
- src/components/Datatable/Table/Table.tsx
- due to having to support both client/server side pagination we have two distinct states for pageIndex and because of this, we had to have the ability to change the page without side effects (`gotoPage` from `react-use-table`) in case the the page number has been changed elsewhere (e.g. filters which is outside the scope of `Table`). 
- when `sortBy` changes reset page index to 0
- when applying filters reset page index to 0
> feat(Table): reset pagination after sort and filter

- src/components/FullscreenModal/FullscreenModal.tsx
- src/components/FullscreenModal/hooks/useModal.tsx
Since the modal content was defined inside the portal component the content was rerendered every time. That caused that all content was unmounted and recreated for every render and thus input fields lost focus and content and table selection was reset.
> fix(FullscreenModal): render portal content only once

- src/components/Filters/components/Select/Select.tsx
Problem: Tags are not removed from the select field if the multi-select field is in the first position and "condition" is the same as the default. (example: "detection method" first in the list). 
Solved by adding a "key" to select elements.
I'm not sure if it's the best solution. I'm open to any better suggestions.
> fix(fep-1808): tags are not removed after click on clearall

- .storybook/main.ts
- .storybook/preview-head.html
- .storybook/preview.tsx
- .storybook/storybook.enums.ts
- package.json
- src/components/Nav/Nav.stories.tsx
- src/components/Nav/Nav.tsx
- yarn.lock
We have decided to deprecate the Nav component in favour of the text variant of the Tabs component. This PR adds info to Storybook and also throws deprecation warning in non-production environments in the console.
> feat(Nav): deprecate Nav and NavItem components

- .storybook/main.ts
- package.json
- yarn.lock
Due to stability issues we'll revert storybook builder back to webpack4.
> chore(storybook): use webpack4 builder for storybook

- src/components/Tabs/Tab.tsx
- src/components/Tabs/Tabs.test.tsx
- src/components/Tabs/Tabs.tsx
- src/components/Tabs/Tabs.types.ts
This PR adds an option to pass custom pattern matching predicate to determine which tab is currently selected. 
By default, the currently selected tab is determined by strict equality between `selectedValue` and Tab `value`. 
But we can provide for example `R.startsWith` as a predicate and in that case, when we have `selectedValue = "overview/section"` then Tab with `value= "overview"` will be marked as selected.
> feat(Tabs): add custom pattern matching for selected tab

- src/components/FullscreenModal/hooks/useModal.ts
This PR fixes the use-case of positioning Tooltip (and other Popup elements) inside FullscreenModal by adding fullscreen size to portal container.
> fix(FullscreenModal): set fullscreen portal size

- src/components/forms/SearchBar/SearchBar.tsx
The issue: With `isValidatedOnSubmit: true` the `onSearch` function was being called even when the input is invalid because `handleOnValidate` was adding the error status in the state variable `isInvalid` which was not updated before submit
Solution: Run validation on every submit and return `hasError` status directly from `handleOnValidate` to check before searching
> fix(SearchBar): run search if validated

- src/components/layout/Padbox/Padbox.tsx
- src/theme/GlobalStyles/GlobalStyles.tsx
- src/utils/space.ts
Padding sizes were restricted due to misunderstanding, therefore those are removed now.
> feat(padding): remove size restriction warning

- src/components/Modal/Modal.tsx
- CloseButton on Modal was inheriting browser button bg color, which was manifesting when using modal without css reset.
- Modal was removing portal container on unmount, which was causing style mismatch on next mount.
> fix(Modal): close button bg, portal removal

- src/components/Datatable/Table/Table.tsx
In order to support initial values for sorting, page size, and index when searching we need to set those values in the store straight away to avoid them being overwritten by defaults.
> fix(DataTable): set default values in datatable reducer

- src/types/customPropTypes.ts
This PR improves custom prop types checking and fixes warnings for SemanticModal.
```
Component.propTypes = {
tupleProp: CustomPropTypes.tuple(SomePropTypes, SomePropTypes).isRequired
}
```
```
tupleProp={undefined} -> Custom type error
tupleProp={null} -> Custom type error
tupleProp={[]} -> Custom type error
tupleProp={[{...}, {...}, {...}]} -> Custom type error
```
```
tupleProp=[{...}, {...}] -> OK
tupleProp=[{...}] -> OK
tupleProp=[undefined, {...}] -> OK
```
> fix: improve custom prop types check

- yarn.lock
This PR fixes CVE-2021-3918 vulnerability of `json-schema`.
> chore(deps): bump json-schema from 0.2.3 to 0.4.0

- src/components/SemanticModal/SemanticModal.tsx
This small PR simplifies jsx part of Semantic Modal component. No functional change.
> refactor(SemanticModal): simplify jsx using primitives

- .github/workflows/CD.yaml
This PR enables testing on node@16 and also fixes not storing visual test artifacts when the test step fails.
> build(actions): run unit tests on node@16

- CONTRIBUTING.md
This PR adds squash commits guideline for contributing on DS
> docs(contributing): add squash commits convention

- src/components/Filters/components/DateRangePicker/styles.ts
- src/utils/helpers.stories.mdx
- src/utils/helpers.test.ts
- src/utils/helpers.ts
This PR removes getBorderRadius method from DS codebase. 
[Closes](https://zitenote.atlassian.net/browse/UXD-393)
> refactor(utils): remove getBorderRadius helper method

- src/components/Breadcrumbs/Breadcrumbs.test.tsx
- src/components/Breadcrumbs/Breadcrumbs.tsx
We decided to change the order of the elements in breadcrumb overflow-dropdown not to be in reverse order. Also, dropdown options list only show the hidden elements, not all breadcrumb items. 
[Closes](https://zitenote.atlassian.net/browse/UXD-211)
> fix(Breadcrumbs): fix order and options showed in dropdown

- src/components/Datatable/Datatable.test.tsx
- src/components/Datatable/Table/Table.tsx
Currently, when any manipulation with data happens (e.g. row is removed), selected row IDs stay selected after that. This PR adds a selection reset whenever table data changes.
Closes UXD-295
> fix(Datatable): reset selection on data change

- package.json
- rollup.config.js
- yarn.lock
This PR adds [npm: rollup-plugin-terser](https://www.npmjs.com/package/rollup-plugin-terser) to reduce bundle size. 
We are using default parameters. 
Tested locally, build/index.es.js seems to reduce almost to half. 
Also, the warning from ssc-ui-core goes away
Before:
After:
[Closes](https://zitenote.atlassian.net/browse/UXD-474)
> chore(bundle): add terser plugin to reduce bundle size

- .github/workflows/CD.yaml
- package.json
- yarn.lock
I did a couple of fixes in the CI to make dependencies and build caches dependent on the node version. I also fixed the issue in the `build` step where CI was using the build from the cache instead of testing if the package can be built correctly.
Since `semantic-release` can be only run on node@14.17+ I had to move it to `optionalDependencies` as it was failing the install on `unit-test` and `build` steps on node@12. With this change, we are saying we are fine if those packages aren't installed since we need them only in the `build-and-publish` step.
Closes UXD-494
> chore(package): upgrade semantic-release ecosystem

- package.json
- yarn.lock
> chore(package): upgrade prismjs to 1.27.0

- src/components/_internal/BaseTabs/BaseTabLabel.tsx
Update hover and pressed state color in Segmented Toggle
[Closes](https://zitenote.atlassian.net/browse/UXD-550)
> fix(SegmentedToggle): fix hover-pressed state colors

- .github/workflows/CD.yaml
- package.json
* replaces Node@12 with Node@18
* upgrades `actions/setup-node` to latest version
* fix some typing inconsistencies
* add uploading bundle stats during the build step
* change handling of visual regression artifacts (tar before upload and upload only when test fails)
* move semantic release back to dev deps to prevent leaking in the consumer's yarn.lock (this was done because installing was filing when used with Node@12)
> build: remove Node@12 tests

- src/types/polymorphicComponent.types.ts
This PR adds types to support polymorphic component props checking. For more info please follow:
https://www.benmvp.com/blog/polymorphic-react-components-typescript/
https://www.benmvp.com/blog/forwarding-refs-polymorphic-react-component-typescript/
> chore(types): add support for polymorphic components

- src/components/forms/SearchBar/SearchBar.tsx
This PR changes the icon positions for SearchBar. 
Basically: 
- I’ve updated the search bar component design as follows
- the search icon is on the left
- when the field has input, a clear button appears on right while processing, and the search icon is replaced by a loading spinner
> feat(Searchbar): set new icon positions for SearchBar

- src/components/_internal/BaseButton/BaseStyledButton.tsx
- src/components/_internal/BaseSingleDatePicker/styles.ts
This PR fixes the `:focus` to `:focus-visible` for the `Button` component and for the buttons at `DatePicker/DatePickerRange.` 
The rest of the components don't need an update because the usage of the focus is correct. 
[Closes](https://zitenote.atlassian.net/browse/UXD-636)
> fix(Button): change focus state behaviour

- src/codeExamples/closeHandlingDrawer.stories.mdx
This PR adds a code example for close handling with `Drawer` component
[Closes](https://zitenote.atlassian.net/browse/UXD-651)
> docs(Drawer): add code example for close handling

- package.json
- yarn.lock
In @emotion/react@11.8.0 was introduced usage of React@18 `useInsertionEffect` with a bug
that was fixed in 11.8.1. But there is still some issue even in 11.9.4 that throws warnings during
the build in platform. Until the issue isresolved we will pin @emotion/react to the latest version
that wasn't using `useInsertionEffect`.
> fix(build): downgrade @emotion/react

- src/components/Filters/Filters.stories.tsx
- src/components/Filters/Filters.tsx
- src/components/Filters/Filters.types.ts
When Filters component is used without Apply button `onError` callback
can be used to determine state of submit button and prevent user from
sending invalid form data.
This callback is called on any change event and takes boolean `hasError`
as first argument.
Closes UXD-856
> feat(Filters): expose onError callback

- src/components/Filters/StateButton/StateButton.tsx
[Filters] StateButton line height is wrong, the padding exceeded the height in the text part of the button.
Before
After
https://zitenote.atlassian.net/browse/UXD-910
> fix: changed line-height to 1rem in state button

- src/components/FileSelector/FileSelector.tsx
- src/components/Filters/hooks/useFilterRow.test.ts
- src/components/Filters/hooks/useFilterRow.ts
- src/components/FullscreenModal/FullscreenModal.tsx
- src/components/Nav/Nav.tsx
- src/components/_internal/BaseButton/BaseButton.tsx
- src/components/_internal/BaseTable/renderers/LinkRenderer.tsx
- src/components/forms/InputGroup/InputGroup.tsx
- src/components/layout/Grid/Grid.tsx
- src/hooks/useLogger.test.tsx
- src/hooks/useLogger.ts
- src/hooks/useWhyDidYouUpdate.ts
- src/managers/BannersManager/BannersProvider.test.tsx
- src/managers/BannersManager/BannersProvider.tsx
- src/managers/common/createCtx.ts
- src/theme/DSProvider/DSProvider.tsx
- src/theme/DSProvider/DSProvider.types.ts
- src/utils/require-router-link.ts
This PR adds `useLogger` hook that return `log`, `warn` and `error` methods. Those methods can be used for guarded logging inside DS.
- `log` method is calling `console.log` when debug mode is enabled in DSProvider config
- `warn` method is calling `console.warn` when the DS is not running in production environment
- `error` method throws an error when DS is not running in production environment and calls `console.error` in production
Closes UXD-970
> feat(logging): implement DS logger

- src/components/SemanticModal/SemanticModal.tsx
- src/components/SemanticModal/SemanticModal.types.ts
Add the `loadingText` property to the `SemanticModal` component.
> feat(SemanticModal): add loading text to the renderButton

- .github/workflows/CD.yaml
- .releaserc.json
- package.json
- scripts/generate-index.js
- yarn.lock
Update to the last attempt to auto-release docs with a new package version.
This time I added a dry-run step for semantic release that will tell us two things:
1) Will a new version be released?
2) What version will be released?
With this knowledge, we can limit documentation release for cases when a new package version is released. The following version number will allow us to version the documentation to provide documentation for previous versions of the Design System.
> build(docs): run docs deploy on release

- src/components/Card/Card.stories.tsx
- src/components/Card/Card.types.ts
- src/components/Card/CardMedia.tsx
implements https://zitenote.atlassian.net/browse/UXD-1016
BREAKING CHANGE: alt attribute needs to be always defined
[UXD-1016]: https://zitenote.atlassian.net/browse/UXD-1016?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(CardMedia): make alt attribute required

- src/components/Breadcrumbs/BreadcrumbItem.tsx
- src/components/Breadcrumbs/Breadcrumbs.tsx
implements https://zitenote.atlassian.net/browse/UXD-1012
removed default list styles
> feat(Breadcrumbs): change children to list items

- src/components/forms/Radio/Radio.tsx
The position:fixed of the hidden input type=radio in the Radio component can cause height calculation issues in parent containers.
This fix ensures the input stays within the limits of its parent container, while avoiding any position bug.
> fix(Radio): wrap component in relative container

- package.json
- src/components/Datatable/index.ts
Back in v1.1.1 we removed unnecessary definition files. This change caused change of structure of the build folder.  We forgot to reflect this change in the types field in package.json. This caused that applications using DS weren't able to pick component types we are distributing with this package.
> fix(types): fix types field

- src/components/Tooltip/Tooltip.test.tsx
- src/components/Tooltip/Tooltip.tsx
If no `popup` was provided Tooltip component showed empty contatiner.
> fix(Tooltip): fix showing empty tooltip

- src/components/Tooltip/Tooltip.tsx
- src/components/Tooltip/Tooltip.types.ts
This change will allow us to use Tooltip component also in SVG elements.
Closes UXD-1370
> feat(Tooltip): allow passing wrapper element

- src/components/Tabs/Tab.tsx
- src/components/Tabs/Tabs.stories.tsx
- src/components/Tabs/Tabs.tsx
- src/components/Tabs/Tabs.types.ts
This PR adds the ability to add the `onClick` handler to the `Tab` component. This property was previously hijacked by the `onSelectTab` passed from the parent component. I also clearly marked internal properties to prevent confusion.
Closes UXD-1384
> feat(Tabs): allow passing onClick to Tab component

- src/components/DatatableV2/Datatable.types.ts
- src/components/DatatableV2/columns.utils.ts
- src/components/DatatableV2/header/HeaderCell.tsx
- src/components/DatatableV2/hooks/useDatatable.ts
- src/components/DatatableV2/hooks/useDisplayColumns.tsx
- src/components/DatatableV2/panels/DetailPanel.tsx
- src/components/DatatableV2/stories/DetailPanel.stories.tsx
- src/components/DatatableV2/stories/HeaderTooltip.stories.tsx
I noticed some minor issues during writing documentation. This PR fixes them.
- removed unnecessary props from TS definitions
- mark column without accessors as 'display' instead of 'data'
- make details panel grow to the full width
- make rows per page default value 50 if selector is not enabled
- fix display column text header styles
> fix(DatatableV2): fix minor issues

- package.json
- src/components/Collapsible/Collapsible.stories.tsx
- src/components/Collapsible/Collapsible.test.tsx
- src/components/Collapsible/Collapsible.tsx
- src/components/Collapsible/Collapsible.types.ts
- yarn.lock
This PR adds support for controlled (external) state management. The component was also internally rewritten to use RadixUI. The `defaultIsOpened` was renamed to `defaultIsOpen` to increase consistency with rest of the API.
Closes UXD-1437
> feat(Collapsible): add controlled mode

- src/components/DatatableV2/header/Header.tsx
If `enableRowSelection` is set to `false` the selection state can still be used. In this case if selection is triggered from outside the table header will dissapear but the batch row will not be showed. This PR will prevent hiding the table header in this case.
> fix(DatatableV2): show header when selection is disabled

- src/hooks/useLockBodyScroll.ts
We observed issue when DS dialog (modal or drawer) were triggered from Radix UI DropdownMenu component (e.g. in DatatableV2 row actions menu). Since Radix UI DropdownMenu is locking body scroll when displayed the original computed style for `<body>` overflow was stored as `hidden` and when the DS dialog was closed the `hidden` were restored as original state. This prevented users to scroll the page without need to reload.
> fix(useLockBodyScroll): fix scroll releasing

- src/components/forms/Checkbox/Checkbox.tsx
- src/components/forms/Select/Select.stories.tsx
- src/components/forms/Select/Select.styles.tsx
This draft PR fixes the issues we've been having with the Multi Select in Risk Control.
Here is the original ticket:
https://zitenote.atlassian.net/browse/MS-287
This draft PR is split separated in 3 commits, so you can checkout each step of the "fix" (which we may want to split across multiple PRs)
1 (`7ac6f4d0`): I created an interactive storybook test with a controlled value where we can remove items from external widgets. This reflects the scenario and issue we face in Risk Control,
2 (`bd7e1c6c`): This simple CSS fix makes the clickable area of the hidden checkbox input the same size as the displayed icon. I hardcoded `pxToRem(20)` (default was 13), but maybe there's a constant for this that we should use. @ajkl2533  ?
before:  
after:
3 (`979917e0`): the presence of the `htmlFor` …
> toggling issues on select with controlled values

- src/components/Drawer/Drawer.test.tsx
- src/components/Dropdown/ControlledDropdown.tsx
When dropdown-like component is used inside dialogs the focus trap prevented from clicking on interactive elements, because dropdowns are rendered into separate portals. This PR adds checking if the dropdown is used in dialog context and if dialog is detected dropdown is not rendered in portal.
> fix(dialogs): render dropdowns in dialog context

- src/components/layout/Stack/Stack.stories.tsx
- src/components/layout/Stack/Stack.tsx
Previous change introduced accidental breaking change extensively described in https://github.com/styled-components/styled-components/issues/2129. We removed wrapping into React component to revert to previous behaviour.
> fix(Stack): allow polymorphic behaviour for extended components

- .storybook/preview.tsx
- docs/localization.mdx
- jest.setup.ts
- src/components/Filters/BottomBar/BottomBar.tsx
- src/components/Filters/FilterRow/FilterRow.tsx
- src/components/Filters/StateButton/StateButton.tsx
- src/components/Filters/components/Count/Count.tsx
- src/components/Filters/components/Input/Input.tsx
- src/components/Filters/components/Integer/Integer.tsx
- src/components/Filters/components/Number/Number.tsx
- src/components/Filters/components/TagsInput/TagsInput.tsx
- src/types/definitions/i18next.d.ts
To prevent accidental clash between existing keys containing ":" we need to change the namespace separator to different character.
> fix(i18n): change namespace separator

- .storybook/preview.tsx
- docs/localization.mdx
- jest.setup.ts
- package.json
- src/locales/cs-CZ.ts
- src/locales/en-US.ts
- src/locales/es-ES.ts
- src/locales/ja-JP.ts
- src/locales/pt-BR.ts
- yarn.lock
> feat(i18n): switch to ICU message format syntax

- src/components/DatatableV2/header/HeaderCell.tsx
If consumer disables the column actions menu the sortion indicator was lost as we have it in the column actions button. This PR adds the separate sorting indicator for cases when the columns actions menu is disabled.
Closes UXD-1644
> fix(DatatableV2): fix missing sorting indicator

- yarn.lock
Fixes https://github.com/securityscorecard/design-system/security/dependabot/98
Ref NOTICKET
> chore(security): upgrade express to fix vulnerability

- .storybook/main.ts
In vite@5.4.12 there was introduced breaking change in order to fix security vulnerability. The CORS protection is enabled by default and it's required to specify hosts that are allowed to connect to the dev server.
> test(storybook): enable docker host in vite config NOTICKET

- src/tokens/color.css
Fixes an issue in which the background color was transparent so the cells look overlap:
Before:
After:
> fix(DatatableV2): fix color hover. MAXX-760

- src/components/DatatableV2/tests/selection.test.tsx
- src/components/_internal/toolbars/SelectionToolbar.tsx
in MAX we want to be able do clear select across all pages in manual pagination mode. Currently, “Clear Selection” only unchecks the rows of the current page.
The behavior is only on the “Clear Selection” button*. The "toggle all" checkbox still only affects the current page.
JIRA ticket: https://zitenote.atlassian.net/jira/software/c/projects/MAXX/boards/2180?assignee=6384d3eb2acfad92d7b2d414&assignee=unassigned&selectedIssue=MAXX-559
https://github.com/user-attachments/assets/f5dad7fc-1a35-451a-b2ca-c27732d95bc7
> feat(DatatableV2): clear all rows in multi-page. MAXX-559

- src/components/DatatableV2/Datatable.types.ts
- src/components/DatatableV2/body/BodyRow.tsx
- src/components/DatatableV2/stories/RowOnClick.stories.tsx
Adding the `MouseEvent` to the `onRowClick` callback in `DataTableV2`.
This will be used to determine if the `meta` or `ctrl` keys are pressed while the user clicks a row.
> feat(DataTableV2): export MouseEvent to onRowClick. MAXX-2015

- package.json
- yarn.lock
- Remove `focus-trap-react` from package.json dependencies
- Reduces bundle size by removing external dependency
- Eliminates transitive dependencies (`focus-trap`, `tabbable`)
> chore(deps): remove focus-trap library. PLAT-928

- src/components/HexGrade/HexGrade.tsx
- src/components/HexGrade/HexGrade.types.ts
I need a prop to pass if the component uses legacy colors. There are cases where the component is used outside the DS provider (echarts), and it uses the experimental styles by default.
I tried wrapping it inside the DSProvider, but it glitches like crazy, and I don't think that's how the provider should be used anyway.
> feat(HexGrade): add isLegacy property.NOTICKET

- src/components/DatatableV2/table/TableRoot.tsx
- src/components/DatatableV2/tests/HorizontalScrollbar.test.tsx
* Deactivate the button when hovering to avoid focus interfering with the mouse event
https://github.com/user-attachments/assets/5967950f-93b3-4663-9942-e86d9751b77f
> fix(focus): horizontal not visible when hover. CORE-561
